CREATE DATABASE IF NOT EXISTS POKEBI;

USE POKEBI;

CREATE TABLE IF NOT EXISTS POKEMON (
    pokedex_number INTEGER NOT NULL, 
    pokemon_name VARCHAR(50) NOT NULL, 
    type_1 VARCHAR(50) NOT NULL, 
    type_2 VARCHAR(50), 
    height INTEGER NOT NULL, 
    weight INTEGER NOT NULL, 
    hit_points INTEGER NOT NULL, 
    attack INTEGER NOT NULL, 
    defense INTEGER NOT NULL, 
    total_stats INTEGER NOT NULL, 
    capture_rate INTEGER NOT NULL, 
    generation INTEGER NOT NULL, 
    base_happiness INTEGER NOT NULL, 
    base_experience INTEGER NOT NULL, 
    exp_type VARCHAR(15), 
    evolves_from VARCHAR(15), 
    mega_evolution BOOLEAN, 
    alolan_form BOOLEAN, 
    galarian_form BOOLEAN, 
    forms_switchable BOOLEAN, 
    legendary BOOLEAN NOT NULL, 
    mythical BOOLEAN NOT NULL, 
    genderless BOOLEAN NOT NULL, 
    female_rate DOUBLE PRECISION NOT NULL, 
    egg_cycles INTEGER, 
    against_normal DOUBLE PRECISION NOT NULL, 
    against_fire DOUBLE PRECISION NOT NULL, 
    against_water DOUBLE PRECISION NOT NULL, 
    against_electric DOUBLE PRECISION NOT NULL, 
    against_grass DOUBLE PRECISION NOT NULL, 
    against_ice DOUBLE PRECISION NOT NULL, 
    against_fighting DOUBLE PRECISION NOT NULL, 
    against_poison DOUBLE PRECISION NOT NULL, 
    against_ground DOUBLE PRECISION NOT NULL, 
    against_flying DOUBLE PRECISION NOT NULL, 
    against_psychic DOUBLE PRECISION NOT NULL, 
    against_bug DOUBLE PRECISION NOT NULL, 
    against_rock DOUBLE PRECISION NOT NULL, 
    against_ghost DOUBLE PRECISION NOT NULL, 
    against_dragon DOUBLE PRECISION NOT NULL,
    against_dark DOUBLE PRECISION NOT NULL, 
    against_steel DOUBLE PRECISION NOT NULL,
    against_fairy DOUBLE PRECISION NOT NULL, 
    
    CONSTRAINT POKEMON_PK PRIMARY KEY (pokedex_number)
)ENGINE = innoDB AUTO_INCREMENT = 1;